apiVersion: v1
kind: Pod #Tipo do recurso
metadata: 
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
     